# Beezig GitLab CI Configuration
# Copyright (C) 2020  Beezig Team
---
image: openjdk:8-alpine

variables:
    VERSION: 7.0.0-rc1

stages:
    - build
    - deploy

build:
    stage: build
    before_script:
        - apk add git
    script:
    - ./gradlew build
    artifacts:
        paths:
            - build/libs/*.jar
        expire_in: 1 week

deploy version:
    stage: deploy
    interruptible: true
    before_script:
        - apk add openssh git jq bash coreutils curl
    script:
        - chmod go= "$DEPLOY_KEY"
        - mkdir -p ~/.ssh/ || true
        - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
        - ssh-agent bash -c "ssh-add \"$DEPLOY_KEY\"; git clone git@gitlab.com:Beezig/version.git ; version/update-version.sh --module beezig-forge --type beta --version $VERSION version/beta.json ; cd version; git add beta.json ; git -c 'user.name=GitLab Deploy' -c 'user.email=noreply@gitlab.com' commit -m 'Update BeezigForge beta version' ; git push origin master"
    only:
        refs:
            - master

trigger laby build:
    stage: deploy
    only:
      - master
    trigger: Beezig/BeezigLaby

.deployments:
    stage: deploy
    interruptible: true
    before_script:
        - apk add openssh git

deploy beta:
    extends: .deployments
    environment:
        name: beta
    script:
        - chmod go= "$DEPLOYMENTS_KEY"
        - mkdir -p ~/.ssh/ || true
        - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
        - "ssh-agent sh -c \"ssh-add \\\"$DEPLOYMENTS_KEY\\\" ; git clone git@gitlab.com:Beezig/deployments.git ; mkdir -p deployments/beezigforge-beta || true ; cp build/libs/BeezigForge*.jar \\\"deployments/beezigforge-beta/BeezigForge-$VERSION-$(git rev-list --count $(git describe --tags --abbrev=0)..HEAD)-$(git log -1 --format=%h).jar\\\" ; cd deployments ; git add . ; git -c 'user.name=GitLab Deploy' -c 'user.email=noreply@gitlab.com' commit -m 'deploy: Deploy BeezigForge Beta' ; git push origin master\""
    only:
        - master
    except:
        - tags

deploy release:
    extends: .deployments
    environment:
        name: release
    script:
        - chmod go= "$DEPLOYMENTS_KEY"
        - mkdir -p ~/.ssh/ || true
        - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
        - "ssh-agent sh -c \"ssh-add \\\"$DEPLOYMENTS_KEY\\\" ; git clone git@gitlab.com:Beezig/deployments.git ; mkdir -p deployments/beezigforge-release || true ; cp build/libs/BeezigForge*.jar deployments/beezigforge-release/BeezigForge-$VERSION.jar ; cd deployments ; git add . ; git -c 'user.name=GitLab Deploy' -c 'user.email=noreply@gitlab.com' commit -m 'deploy: Deploy BeezigForge Release' ; git push origin master\""
    when: manual
    only:
        - tags
...
