language: java
jdk:
  - openjdk8
install: gradle setupCIWorkspace build
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: build/libs/
    github_token: $GITHUB_TOKEN
    repo: RoccoDev/Beezig-Deploy
    target_branch: BeezigForge-$TRAVIS_BRANCH
    on:
     all_branches: true
tags: false